name: client_module
description: Client module for car wash booking MVP-0
publish_to: none

version: 0.1.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^1.2.2
  url_launcher: ^6.3.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.6
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/services/
    - assets/images/logo/
    - assets/images/cars/
    - assets/images/body/
    
